name: TypeScript CI Example

on: 
  push:
    paths:
      - 'source/**'
      - '.eslintrc.json'
      - 'tsconfig.json'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/build.yml'
      - 'Dockerfile'
    branches:
      - '**'

env: 
  ARTIFACT_NAME: TypeScript-CI-Example

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      
      - name: Install Dependencies
        run: npm install

      - name: Lint using ESlint
        run: npx eslint ./source/

      - name: Compile TypesScript
        run: npx tsc

      - name: Run Tests
        run: npm test
      
      - name: Upload Code
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: |
            ./emit
            package.json
            package-lock.json
 
  docker:
    name: Docker
    runs-on: ubuntu-22.04
    needs: build
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY_NAME: ghcr.io
    steps: 
    - name: Clone repo
      uses: actions/checkout@v3


    - name: Download Code
      uses: actions/download-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ./code/
      
    - name: Setup Docker
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/amd64

    - name: Login to Docker
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY_NAME }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
      
          
    - name: Build Docker Image
      uses: docker/build-push-action@v3
      with:
        file: ./Dockerfile
        context: ./code/
        tags: ${{ env.REGISTRY_NAME }}/${{ github.repository_owner }}/ci-example:latest
        push: true
      
    - name: Cleanup Docker Images
      uses: snok/container-retention-policy@v1
      with:
        image-names: ci-example
        cut-off: 0 seconds ago UTC
        keep-at-least: 1
        untagged-only: true
        account-type: personal
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN_PACKAGES }}
        